short_forms = {
    "hlo": "hello",
    "wyd": "what are you doing",
    "wdym": "what do you mean",
    "idk": "I don't know",
    "brb": "be right back",
    "ty": "thank you",
    "np": "no problem",
    "omg": "oh my god",
    "tbh": "to be honest",
    "imo": "in my opinion",
    
    # Greetings
    "hlo": "hello",
    "hey": "hello",
    "gm": "good morning",
    "gn": "good night",
    "tc": "take care",
    
    # Questions
    "wyd": "what are you doing",
    "wdym": "what do you mean",
    "sup": "what's up",
    "hru": "how are you",
    "yolo": "you only live once",
    "idk": "I don't know",
    "ikr": "I know right",
    "tldr": "too long didn't read",
    "fyi": "for your information",
    "faq": "frequently asked questions",
    "asap": "as soon as possible",
    
    # Affirmations & Reactions
    "np": "no problem",
    "yw": "you're welcome",
    "ty": "thank you",
    "thx": "thanks",
    "k": "okay",
    "kk": "okay",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "lmao": "laughing my ass off",
    "smh": "shaking my head",
    "oof": "ouch",
    "gg": "good game",
    "brb": "be right back",
    "bbl": "be back later",
    "ttyl": "talk to you later",
    "np": "no problem",
    "nvm": "never mind",
    
    # Emotions
    "tbh": "to be honest",
    "imo": "in my opinion",
    "idc": "I don't care",
    "fomo": "fear of missing out",
    "afk": "away from keyboard",
    "irl": "in real life",
    "hbd": "happy birthday",
    "ily": "I love you",
    "ilu": "I love you",
    "wb": "welcome back",
    "gr8": "great",
    "bff": "best friends forever",
    "ftw": "for the win",
    
    # Internet Slang
    "btw": "by the way",
    "omw": "on my way",
    "bday": "birthday",
    "tho": "though",
    "prolly": "probably",
    "w/e": "whatever",
    "l8r": "later",
    "thru": "through",
    "pls": "please",
    "sry": "sorry",
    "u": "you",
    "r": "are",
    "b": "be",
    "g2g": "got to go",
    "cya": "see you",
    "u2": "you too",
    
    # Tech/Work
    "gtg": "got to go",
    "imo": "in my opinion",
    "bfn": "bye for now",
    "otp": "on the phone",
    "msg": "message",
    "dm": "direct message",
    "rt": "retweet",
    "lmkwyt": "let me know what you think",
    "lmk": "let me know",
    "jk": "just kidding",
    "wfh": "work from home",
    "tysm": "thank you so much",
    
    # Gaming
    "glhf": "good luck have fun",
    "afk": "away from keyboard",
    "ez": "easy",
    "pog": "play of the game",
    "wp": "well played",
    "noob": "newbie",
    "op": "overpowered",
    "ggwp": "good game well played",
    
    # Social Media & Trends
    "bae": "before anyone else",
    "ft": "featuring",
    "nsfw": "not safe for work",
    "oml": "oh my lord",
    "smth": "something",
    "tmrw": "tomorrow",
    "rn": "right now",
    "btw": "by the way",
    "bio": "biography",
    "imo": "in my opinion",
    "idc": "I don't care",
    "wbu": "what about you",
    "xoxo": "hugs and kisses"
}